import MantineStylesProvider from './MantineStyles'
import { AppShell } from './components/layout/app-shell'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <MantineStylesProvider>
          <AppShell>
            {children}
          </AppShell>
        </MantineStylesProvider>
      </body>
    </html>
  )
}
